//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sondeo_web_7eam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class PRODUCTO
    {
        [Required]
        [Index(IsUnique = true)]
        [Display(Name = "Ingrese el ID del producto")]
        public int ID_PRODUCTO { get; set; }
        [Required]
        [Display(Name = "Seleccione el ID de su Categoria")]
        public int ID_CATEGORIA { get; set; }
        [Required]
        [Display(Name = "Ingrese su Unidad de Medida ")]
        public Nullable<int> UNIDAD_MEDIDA { get; set; }
        [Required]
        [Display(Name = "Seleccione el ID de la Marca del producto")]
        public int ID_MARCA { get; set; }
        [Required]
        [Display(Name = "Ingrese el nombre del Producto")]
        public string PRODUCTO1 { get; set; }
        [Required]
        [Display(Name = "Ingrese el tamaño de la presentación")]
        public string PRESENTACION { get; set; }
        [Required]
        [Display(Name = "Ingrese el precio del Producto")]
        public decimal PRECIO_CONSULTA { get; set; }
        [Required]
        [Display(Name = "Ingrese el tipo del Producto en esa Presentacion")]
        public string TIPO { get; set; }
        public Nullable<bool> ALPORMAYOR { get; set; }
        public int ID_SONDEO { get; set; }
        [Required]
        [Display(Name = "Ingrese el Peso del Producto( En su Unidad de Medida)")]
        public Nullable<decimal> CANTIDAD_MEDIDA { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual MARCA MARCA { get; set; }
        public virtual MEDIDA MEDIDA { get; set; }
        public virtual SONDEO SONDEO { get; set; }
    }
}
