//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sondeo_web_7eam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public int ID_PRODUCTO { get; set; }
        public Nullable<int> ID_CATEGORIA { get; set; }
        public Nullable<int> UNIDAD_MEDIDA { get; set; }
        public Nullable<int> ID_MARCA { get; set; }
        public string PRODUCTO1 { get; set; }
        public string PRESENTACION { get; set; }
        public decimal PRECIO_CONSULTA { get; set; }
        public string TIPO { get; set; }
        public bool ALPORMAYOR { get; set; }
        public int ID_SONDEO { get; set; }
        public decimal CANTIDAD_MEDIDA { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual MARCA MARCA { get; set; }
        public virtual MEDIDA MEDIDA { get; set; }
        public virtual SONDEO SONDEO { get; set; }
    }
}
