//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sondeo_web_7eam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTE
    {
        public string ID_REPORTE { get; set; }
        public string ID_SONDEO { get; set; }
        public string ID_USUARIO { get; set; }
        public System.DateTime FECHA_REPORTE { get; set; }
    
        public virtual SONDEO SONDEO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
