//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sondeo_web_7eam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SONDEO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SONDEO()
        {
            this.ProductosEnSondeo = new HashSet<ProductosEnSondeo>();
            this.REPORTE = new HashSet<REPORTE>();
        }
    
        public string ID_SONDEO { get; set; }
        public int ID_LOCAL { get; set; }
        public System.DateTime FECHA { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual LOCALIZACION LOCALIZACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductosEnSondeo> ProductosEnSondeo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPORTE> REPORTE { get; set; }
    }
}
